<h1><?php echo $this->titulo; ?></h1>

<!-- formulário -->

<form id="formUsu" action="/usuario/salvar/id_usuario/<?=$this->usuario['id_usuario']?>" method="post" enctype="multipart/form-data">
    <div class="formfield">
        <label for="">Nome:</label>
        <input class="required" id="usuario-login" name="usuario[login]" type="text" size="50" value=""/>
    </div>    

    <div class="formfield">        
        <label for="">Tipo:</label>
        <?php echo $this->formSelect('usuario[tipo_usuario]', $this->usuario['tipo_usuario'], array('class' => 'required'), array(''=>'SELECIONE', 'A'=>'ADMINISTRADOR', 'C' => 'COMUM')); ?>                
    </div>

    <div class="formfield">
        <label for="">Senha:</label>
        <input  class="required" id="usuario-senha" name="usuario[senha]" type="password" value=""/>
    </div>
    <div class="formfield">
        <label for="">Confirmar Senha:</label>
        <input  class="required" equalTo="#usuario-senha" id="senha2" name="" type="password" value=""/>
    </div>
    <div class="formbutton">
        <input id="btEnviar" type="submit" value="Enviar" />
        <button type="button" id="btVoltarUsuario">Voltar</button> 
    </div>
</form>

<div id="sucessoUsu">
    <p>Sucesso</p>
</div>


<script>
    var dataForm = <?php echo Zend_Json::encode(array('usuario' => $this->usuario)); ?>;
    
    $(function() {        
        $( "#sucessoUsu" ).dialog({
            autoOpen: false
        });
       
        $('#formUsu').populate(dataForm);
        <?php if(!empty($this->usuario['senha'])) { ?>
              $('#senha2').val('<?=$this->usuario['senha']?>');  
        <?php } ?>
            
        $('#formUsu').validate({
            submitHandler: function(form){
                jQuery(form).ajaxSubmit({
                    dataType:  'json', 
                    success: function(r){
                        if(r.tipo == 'sucesso'){                    
                            $('#sucessoUsu p').html(r.msg);                            
                            $( "#sucessoUsu" ).dialog({
                                modal: true,
                                buttons: {
                                    Ok: function() {
                                        $(this).dialog("close");
                                        window.location = r.url;
                                    }
                                }
                            });
                            $('#sucessoUsu').dialog("open");
                            //$('#divMsg').html(r.msg)
                            //window.location = r.url;
                        } else {
                            $('#sucessoUsu p').html(r.msg);                            
                            $( "#sucessoUsu" ).dialog({
                                modal: true,
                                buttons: {
                                    Ok: function() {
                                        $(this).dialog("close");
                                        //window.location = r.url;
                                    }
                                }
                                
                            });
                            $('#sucessoUsu').dialog("open");
                        }
          
                    } 
                });
            }
        });
        
        $('#btVoltarUsuario').click(function(){
            $('#ui-tabs-3').load('/usuario/index/menu/3');
        })
        
        
    });
</script>