<h1><?php echo $this->titulo; ?></h1>

<!-- formulário -->

<form id="formUsu" action="/usuario/salvar" method="post" enctype="multipart/form-data">
    <div class="formfield">
        <label for="">Nome:</label>
        <input class="required" id="nome" name="nome" type="text" size="50" value=""/>
    </div>
    <!--<div class="formfield">
        <label for="">E-mail:</label>
        <input class="required email" id="email" name="email" type="text"  size="50" value="" />
    </div>-->

    <div class="formfield">
        <label for="">Tipo:</label>
        <select name="tipo">
            <option selected value="Selecione">Selecione</option>
            <option value="comum">Comum</option>
            <option value="admin">Administrador</option>
        </select>
    </div>

    <div class="formfield">
        <label for="">Senha:</label>
        <input  class="required" id="senha" name="senha" type="password" value=""/>
    </div>
    <div class="formfield">
        <label for="">Confirmar Senha:</label>
        <input  class="required" equalTo="#senha" id="senha2" name="" type="password" value=""/>
    </div>
    <div class="formbutton">
        <input id="btEnviar" type="submit" value="Enviar" />
        <button type="button" id="btVoltarUsuario">Voltar</button> 
    </div>
</form>

<div id="sucessoUsu">
    <p>Sucesso</p>
</div>


<script>

    $(function(){
        
        $( "#sucessoUsu" ).dialog({
            autoOpen: false
        });
        
        //$('#form').populate(dataForm);
        
        $('#formUsu').validate({
            submitHandler: function(form){
                jQuery(form).ajaxSubmit({
                    dataType:  'json', 
                    success: function(r){
                        if(r.tipo == 'sucesso'){                    
                            $('#sucessoUsu p').html(r.msg);
                            $('#sucessoUsu').dialog("open");
                            $( "#sucessoUsu" ).dialog({
                                modal: true,
                                buttons: {
                                    Ok: function() {
                                        $(this).dialog("close");
                                        window.location = r.url;
                                    }
                                }
                            });
                            
                            //$('#divMsg').html(r.msg)
                            //window.location = r.url;
                        } else {
                            $('#sucessoUsu p').html(r.msg);
                            $('#sucessoUsu').dialog("open");
                            $( "#sucessoUsu" ).dialog({
                                modal: true,
                                buttons: {
                                    Ok: function() {
                                        $(this).dialog("close");
                                        window.location = r.url;
                                    }
                                }
                                
                            });
                        }
          
                    } 
                });
            }
        });
        
        $('#btVoltarUsuario').click(function(){
            $('#ui-tabs-3').load('/usuario/index/menu/1');
        })
        
        
    });
</script>