<h1><?php echo $this->titulo; ?></h1>

<!--<h01>Relatório Teste</h01>

<div class="formbutton">
    <button type="button" id="btGerarRelatorioTeste">Gerar Relatório</button> 
</div>-->

<div id="menuRelatorios">
    <h3>Relatório de Mercadorias</h3>
    <div>
        <form action="" method=get">            
            <div class="formfield">
                <label for="">Tipo:</label>
                <?php echo $this->formSelect('relatorio_mercadoria[id_tipomercadoria]', '', null, $this->dadosComboTipoMercadoria); ?>        
            </div>

            <div class="formfield">
                <label for="">Subtipo:</label>
                <?php echo $this->formSelect('relatorio_mercadoria[id_subtipomercadoria]', '', null, array(''=>'')); ?>        
            </div>

            <div class="formbutton">
                <button id="btGerarRelatorioMercadorias" type="button">Gerar Relatório</button>                
            </div>
        </form>
    </div>
    
    <h3>Section 2</h3>
    <div>
    <p>
    Sed non urna. Donec et ante. Phasellus eu ligula. Vestibulum sit amet
    purus. Vivamus hendrerit, dolor at aliquet laoreet, mauris turpis porttitor
    velit, faucibus interdum tellus libero ac justo. Vivamus non quam. In
    suscipit faucibus urna.
    </p>
    </div>
    <h3>Section 3</h3>
    <div>
    <p>
    Nam enim risus, molestie et, porta ac, aliquam ac, risus. Quisque lobortis.
    Phasellus pellentesque purus in massa. Aenean in pede. Phasellus ac libero
    ac tellus pellentesque semper. Sed ac felis. Sed commodo, magna quis
    lacinia ornare, quam ante aliquam nisi, eu iaculis leo purus venenatis dui.
    </p>
    <ul>
    <li>List item one</li>
    <li>List item two</li>
    <li>List item three</li>
    </ul>
    </div>
    <h3>Section 4</h3>
    <div>
    <p>
    Cras dictum. Pellentesque habitant morbi tristique senectus et netus
    et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in
    faucibus orci luctus et ultrices posuere cubilia Curae; Aenean lacinia
    mauris vel est.
    </p>
    <p>
    Suspendisse eu nisl. Nullam ut libero. Integer dignissim consequat lectus.
    Class aptent taciti sociosqu ad litora torquent per conubia nostra, per
    inceptos himenaeos.
    </p>
    </div>

</div>

<script>
    $(function(){
        //Melhora aparência dos botões
        $("input[type=submit], button").button();
        
        $("#menuRelatorios").accordion();
        
        //Combo de tipo mercadoria popula o combo do subtipomercadoria
        $('#relatorio_mercadoria-id_tipomercadoria').change(function(){
            if($('#relatorio_mercadoria-id_tipomercadoria').val() != '') {
                jsonComboSubTipoMercadoria = $.getJSON('/subtipo/json-combo-subtipomercadoria/id_tipomercadoria/' + $(this).val(), null, function(data){
                    $('#relatorio_mercadoria-id_subtipomercadoria').populateSelectJson(data);                

                    /** se existir apenas 1 registros no retorno da combo, então seleciona esse registro e dispara o onchange da combo*/
                    if($('#relatorio_mercadoria-id_subtipomercadoria').find('option[value!=""]').length == 1){
                        $('#relatorio_mercadoria-id_subtipomercadoria').find('option[value!=""]:first').attr('SELECTED',true);
                        $('#relatorio_mercadoria-id_subtipomercadoria').change();
                    }               
                });
            }            
        });
        
        $("#btGerarRelatorioMercadorias").click(function(){
            id_tipomercadoria = $('#relatorio_mercadoria-id_tipomercadoria').val();
            id_subtipomercadoria = $('#relatorio_mercadoria-id_subtipomercadoria').val();
            window.open('/relatorio/relatorio-mercadorias/id_tipomercadoria/' + id_tipomercadoria + '/id_subtipomercadoria/' + id_subtipomercadoria);
            //$('#ui-tabs-12').load('/relatorio/teste');
            //alert('teste');
        });
        
        
        $("#btGerarRelatorioTeste").click(function(){
            window.open('/relatorio/teste');
            //$('#ui-tabs-12').load('/relatorio/teste');
            //alert('teste');
        });
       
    });
</script>