<?php
/** incia a captura do conteudo que sera renderizado como PDF */
ob_start();
?>
<style type="text/css">            
    .styleTD
    {
        font-size:10px; 
        border-bottom:1px solid #000000; 
        border-right:1px solid #000000; 
        padding:2px; 
        border-top:0px;
    }
    
    .styleTDTitulo
    {
        font-size:10px; 
        border-bottom:1px solid #000000; 
        border-right:1px solid #000000; 
        padding:2px; 
        border-top:1px solid #000000;
        background-color: #74b2e2;
    }         
</style>

<page backtop="7mm" backbottom="7mm" backleft="7mm" backright="7mm" style="font-size: 10pt">
    <page_header>
        <table style="border: solid 1px #000000; border-top:0px; border-left:0px; border-right:0px; border-bottom: 0px; padding: 5px; width: 100%; text-align: center;">
            <tr>           
                <td style="width: 100%; font-size: 16px;">
                    <b><?php echo strtoupper("SISTEMA LOJA") ?></b>                                                          
                </td>               
            </tr>            
        </table>
    </page_header>
    
    <page_footer>
        <table style="width: 100%; border: solid 1px black;">
            <tr>
                <td style="text-align: left;	width: 50%"><?php echo $this->utf8("Relatório de Vendas por Período")->decode(); ?></td>
                <td style="text-align: right;	width: 50%"><?php echo $this->utf8("Página")->decode(); ?> [[page_cu]] de [[page_nb]]</td>
            </tr>
        </table>
    </page_footer>

    <br/><br/>

    <div style="text-align: center; width: 100%; font-weight: bold; font-size: 16px;">
        <?php echo $this->utf8("RELATÓRIO DE VENDAS POR PERÍODO")->decode(); ?>
    </div>

    <br/><br/>   

    <br/><br/>
    
    <b>Per&iacute;odo: </b>
    <?php 
        if(!empty($this->params['data_inicial'])) {
            echo $this->String($this->params['data_inicial'])->reverseDate();
        } else {
            echo "__/__/____";
        }       
    ?>
    &agrave;
    <?php 
        if(!empty($this->params['data_final'])) {
            echo $this->String($this->params['data_final'])->reverseDate();
        } else {
            echo "__/__/____";
        }       
    ?>
    <br/><br/>
    <table border='1' style='border:1px solid #000000; border-collapse:collapse; font-size:9px;'>
        <thead>
        <tr style="font-size: 12;">
            <th class="styleTDTitulo" style="text-align: center">
                Cliente
            </th>
            <th class="styleTDTitulo" style="text-align: center">
                Data Realiza&ccedil;&atilde;o
            </th>
            <th class="styleTDTitulo" style="text-align: center">
                Valor Total
            </th>
            <th class="styleTDTitulo" style="text-align: center">
                Valor Desconto 
            </th>  
            <th class="styleTDTitulo" style="text-align: center">
                Forma
            </th> 
        </tr>
        </thead>
        
        <?php
        
        $widthCliente = 'width: 300px';
        $widthData = 'width: 170px';
        $widthValorTotal = 'width: 100px';
        $widthValorDesconto = 'width: 100px';
        $widthForma = 'width: 200px';
        
        
        if (!empty($this->dataVendas)) {
            //Para fazer linhas cor sim cornão
            $exibe_cor = false;            
            
            $somaValorTotal = 0.0;
            $somaValorDesconto = 0.0;
            
            foreach ($this->dataVendas as $venda) {
                //Para fazer linhas cor sim cornão
                if ($exibe_cor) {
                    $cor = '#F0FFFF';
                    $exibe_cor = false;
                } else {
                    $cor = '#FFFFFF';
                    $exibe_cor = true;
                }                                
                
                $somaValorTotal += $venda['valor_total_venda'];
                $somaValorDesconto += $venda['valor_desconto'];
            ?>
                <tr>
                    <td style="<?=$widthCliente?>;background-color:<?php echo $cor ?>">
                        <?php 
                            echo $venda['nome']; 
                        ?>
                    </td>
                    <td style="<?=$widthData?>;text-align: center;background-color:<?php echo $cor ?>">
                        <?= $this->String($venda['data_venda'])->reverseDate(); ?>
                    </td>
                    <td style="<?=$widthValorTotal?>;text-align: center;background-color:<?php echo $cor ?>">
                        <?= $this->String($venda['valor_total_venda'])->floatToMoney(); ?>
                    </td>
                    <td style="<?=$widthValorDesconto?>;text-align: center;background-color:<?php echo $cor ?>">
                        <?= $this->String($venda['valor_desconto'])->floatToMoney(); ?>
                    </td>
                    <td style="<?=$widthForma?>;text-align: left;background-color:<?php echo $cor ?>">
                        <?php
                            if($venda['tipo_pagamento'] == 'V') {
                                echo "A VISTA";
                            } else {
                                echo "A PRAZO";
                            }
                            echo " / ";
                            if($venda['forma_pagamento'] == 'D') {
                                echo "DINHEIRO";
                            } else {
                                if($venda['forma_pagamento'] == 'CC') {
                                    echo $this->utf8("CARTÃO DE CRÉDITO")->decode();
                                } else {
                                    echo $this->utf8("CARTÃO DE DÉBITO")->decode();
                                }
                            }
                        ?>
                    </td>
                </tr>                
            <?php
                
            }                                    
            ?>                            
                <tr>
                    <td colspan="2" style="text-align: right;background-color:#CDCDB4">
                        <b>TOTAL</b>
                    </td>
                    <td  style="text-align: center;background-color:#CDCDB4">
                        <b><?= $this->String($somaValorTotal)->floatToMoney()?></b>
                    </td>                    
                    <td  style="text-align: center;background-color:#CDCDB4">
                        <b><?= $this->String($somaValorDesconto)->floatToMoney()?></b>
                    </td>
                    <td style="text-align: right;background-color:#CDCDB4">
                        &nbsp;
                    </td>
                </tr>                                
        <?php        
        } else {
        ?>            
            <tr>
                <td colspan="5" class="styleTD" style="width: 680px;">
                    Nenhuma venda encontrada, tente escolher outros filtros e gere novamente o relat&oacute;rio.
                </td>
            </tr>           
        <?php } ?>
    </table>
</page>

<?php
/** finaliza a captura do conteudo */

$content = ob_get_clean();
/** renderiza o PDF */
$orientation = 'L'; //L = PAISAGEM
//P = Porta Retrato
/** renderiza o PDF */
$this->pdf($content, 'RELATORIO_VENDAS.pdf', null, $orientation);
?>
