<h1><?php echo $this->titulo; ?></h1>

<!-- formulário -->

<form id="formVenda" action="/venda/salvar/id_venda/<?=$this->venda['id_venda']?>" method="post" enctype="multipart/form-data">
    <div class="formfield">
        <label for="">Cliente:</label>
        <input class="required" id="venda-id_cliente" name="venda[id_cliente]" type="hidden" size="69" value=""/>
        <input class="required" id="venda-nome" name="venda[nome]" type="text" size="69" value=""/>
    </div>

    <div id="produto" class="formfield">
        <label for="">Produto:</label>
        <input class="required" id="produto" name="produto" type="text" size="50" value=""/>
        <label style="width: 100px" for="">&nbsp;&nbsp;Quantidade:</label>
        <input class="required" id="qtde" name="qtde" type="text" size="5" value=""/>
        <a id="btAdicionar" style="cursor: pointer">
            &nbsp;&nbsp;&nbsp;<img src="/img/add_256.png" width="20" height="20" title="Adicionar Produto" />
        </a>
    </div>

    <div id="teste">
        
        
    </div>
    
    <div class="formfield">
        <label for="">Tipo de Pagamento:</label>
        <?php echo $this->formSelect('venda[tipo_pagamento]', $this->venda['tipo_pagamento'], array('class' => 'required'), array(''=>'SELECIONE','V'=>'A VISTA', 'P' => 'A PRAZO')); ?>
        
    </div>

    <div class="formfield">
        <label for="">Forma de Pagamento:</label>
        <?php echo $this->formSelect('venda[forma_pagamento]', $this->venda['forma_pagamento'], array('class' => 'required'), array(''=>'SELECIONE', 'D'=>'DINHEIRO', 'CC' => 'CARTÃO DE CRÉDITO', 'CD' => 'CARTÃO DE DÉBITO')); ?>
        
    </div>

    <div class="formfield">
        <label for="">Desconto:</label>
        <input id="venda-valor_desconto" class="money" name="venda[valor_desconto]" type="text" size="21px" value=""/>
    </div>
    
    <div class="formfield">
        <label for="">Valor Total:</label>
        <input id="venda-valor_total_venda" class="required money" name="venda[valor_total_venda]" type="text" size="21px" value=""/>
    </div>

    <div class="formfield">
        <label for="">Data:</label>
        <input class="required" id="venda-data_venda" name="venda[data_venda]" type="text" size="21px" value=""/>
    </div>

    <div class="formbutton">
        <input id="btEnviar" type="submit" value="Enviar" />
        <button type="button" id="btVoltarVenda">Voltar</button> 
    </div>
</form>

<div id="sucessoVenda">
    <p>Sucesso</p>
</div>


<script>
    var dataForm = <?php echo Zend_Json::encode(array('venda' => $this->venda)) ?>;
    $(function(){                
        $('#formVenda').populate(dataForm);
        
        $('.money').maskMoney({
            allowZero:true,
            decimal:",", 
            thousands:".", 
            defaultZero:false
        });
        $('#venda-data_venda').mask("99/99/9999");
        $('#venda-data_venda').datepicker({dateFormat:'dd/mm/yy'});
        
        $('#sucessoVenda').dialog({
            autoOpen: false
        });
        
        //$('#form').populate(dataForm);
        
        $('#formVenda').validate({
            submitHandler: function(form){
                jQuery(form).ajaxSubmit({
                    dataType:  'json', 
                    success: function(r){
                        if(r.tipo == 'sucesso'){                    
                            $('#sucessoVenda p').html(r.msg);
                            $('#sucessoVenda').dialog("open");
                            $( "#sucessoVenda" ).dialog({
                                modal: true,
                                buttons: {
                                    Ok: function() {
                                        $(this).dialog("close");
                                        window.location = r.url;
                                    }
                                }
                            });
                            
                            //$('#divMsg').html(r.msg)
                            //window.location = r.url;
                        } else {
                            $('#sucessoVenda p').html(r.msg);
                            $('#sucessoVenda').dialog("open");
                            $( "#sucessoVenda" ).dialog({
                                modal: true,
                                buttons: {
                                    Ok: function() {
                                        $(this).dialog("close");
                                        window.location = r.url;
                                    }
                                }
                                
                            });
                        }
          
                    } 
                });
            }
        });
        
        $('#btVoltarVenda').click(function(){
            $('#ui-tabs-1').load('/venda/index/menu/1');
        })
        
        var html;
        
        html = "<div class='formfield'>" +
            "<label for=''>Produto:</label>" +
            "<input class='required' id='produto' name='produto' type='text' size='50'/>" +
            "<label style='width: 100px' for=''>&nbsp;&nbsp;Quantidade:</label>" +
            "<input class='required' id='qtde' name='qtde' type='text' size='5 value=''/>" +
            "<a id='btRemover' onClick='removerItem(this)' style='cursor: pointer'>" +
            "&nbsp;&nbsp;<img src='/img/symbol_remove.png' width='30' height='30' title='Remover Produto' />" +
            "</a>" +
            "</div>";
        
        $('#btAdicionar').click(function(){
            $("#teste").append(html);
        });
                               
    });
    
    function removerItem(obj) {
        $(obj).parent().remove();
        //alert("a");
    }
</script>