<table>
    <tr>
        <th>Data</th>
        <th>Cliente</th>
        <th>Valor total</th>
        <th>Forma Pagamento</th>
        <th>Tipo Pagamento</th>
        <th>Ações</th>
    </tr>

    <tr class="alt" >
        <?php foreach ($this->paginator as $k => $venda): ?>
        <tr class="<?php echo ($k % 2 == 0) ? 'alt' : '' ?>">
            <td><?php echo $this->String($venda['data_venda'])->reverseDate(); ?></td>
            <td><?php echo $venda['nome'] ?></td>
            <td><?php echo $this->String($venda['valor_total_venda'])->floatToMoney(); ?></td>
            <td>
                <?php 
                    if($venda['tipo_pagamento'] == "V") {
                        echo "A VISTA";
                    }
                    if($venda['tipo_pagamento'] == "P") {
                        echo "A PRAZO";
                    }                                      
                ?>
            </td>
            <td>
                <?php 
                    if($venda['forma_pagamento'] == "D") {
                        echo "DINHEIRO";
                    } 
                    if($venda['forma_pagamento'] == "CC") {
                        echo "CARTÃO DE CRÉDITO";
                    }
                    if($venda['forma_pagamento'] == "CD") {
                        echo "CARTÃO DE DÉBITO";
                    }                                        
                ?>
            </td>
            <td>
                <a class="linkEditar" href="/venda/formulario/id_venda/<?php echo $venda['id_venda'] ?>">
                    <img src="/img/edit-icon.gif" title="Editar registro" />
                </a>
                <a class="btExcluir" href="/venda/excluir/id_venda/<?php echo $venda['id_venda'] ?>">
                    <img src="/img/delete-icon.gif" title="Excluir Registro" />
                </a>
               <?php if($venda['forma_pagamento'] == "D" && $venda['tipo_pagamento'] == "P") { ?>
                  <a class="btConsultarVenda" href="/venda/consultar/id_venda/<?php echo $venda['id_venda'] ?>">
                    <img src="/img/lupa.png" title="Consultar Registro" />
                  </a> 
               <?php }?>
            </td>
        </tr>    
    <?php endforeach; ?>

</table>

<?php echo $this->paginationControl($this->paginator, 'Sliding', 'my_pagination_control.phtml'); ?>

<div id="dcVenda">
    <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>Deseja realmente excluir essa Venda?</p>
</div>

<div id="vendaErro">
    <p></p>    
</div>

<div id="vendaSucesso">
    <p></p>    
</div>

<script>
    
    var url = "";
    $(function(){       
                
        $( "#compraSucesso" ).dialog({
            autoOpen: false
        });
        
        $( "#compraErro" ).dialog({
            autoOpen: false
        });
                
        $("#dcVenda").dialog({
            resizable: false,
            height:250,
            width:500,
            modal: true,
            autoOpen: false,
                
            buttons: {
                "Ok": function() {
                    $.get(url, null, function(retorno){
                        if(retorno.tipo == 'sucesso'){
                            $('#vendaSucesso').html(retorno.msg);                            
                            $('#vendaSucesso').dialog({
                                modal: true,
                                autoOpen: false,
                                buttons: {
                                    "Ok": function() {
                                        $(this).dialog("close");
                                    }
                                }
                            }); 
                            $('#vendaSucesso').dialog("open");
                            $('#divResVenda').load('/venda/grid/');                                
                        } else {
                            $('#vendaErro').html(retorno.msg);                            
                            $('#vendaErro').dialog({
                                modal: true,
                                autoOpen: false,
                                buttons: {                                    
                                    "Ok": function() {
                                        $(this).dialog("close");
                                    }
                                }
                            });
                            $('#vendaErro').dialog("open");
                            $('#divResVenda').load('/venda/grid/');
                        }                    
                    }, 'json');
                    $(this).dialog("close");                   
                },
                Cancel: function() {
                    $('#divResVenda').load('/venda/grid/');
                    $( this ).dialog( "close" );
                        
                }
                    
            }
                
        });
                
        $('.pagination a').click(function(){           
            var href = $(this).attr('href');
            $('#divResVenda').load(href);
            return false;
        });
        
        $('.linkEditar').click(function(){
            var url = $(this).attr('href');
            $('#ui-tabs-1').load(url);
            return false;
        });
        $('.btConsultarVenda').click(function(){
            var url = $(this).attr('href');
            $('#ui-tabs-1').load(url);
            return false;
        });
        
        $('.btExcluir').click(function(){            
            url = $(this).attr('href');
            $("#dcVenda").dialog("open");            
            return false;
        });
        
    })
    
</script>