<h1><?php echo $this->titulo; ?></h1>

<!-- formulário -->

<form id="formVenda" action="/venda/salvar/id_venda/<?=$this->venda['id_venda']?>" method="post" enctype="multipart/form-data">
    <div class="formfield">
        <label for="">Cliente:</label>
        <input class="required" id="venda-id_cliente" name="venda[id_cliente]" type="hidden" value=""/>
        <input class="required" id="venda-nome" name="venda[nome]" type="text" size="44" value=""/>
        
        <label for="" style="width: 50px;">&nbsp;&nbsp;Data:</label>
        <input class="required" id="venda-data_venda" name="venda[data_venda]" type="text" size="21px" value=""/>
    </div>

    <div id="produto" class="formfield">
        <label for="">Produto:</label>
        <input class="required" id="produto" name="produto" type="text" size="50" value=""/>
        <label style="width: 100px" for="">&nbsp;&nbsp;Quantidade:</label>
        <input class="required" id="qtde" name="qtde" type="text" size="5" value=""/>
        <a id="btAdicionar" style="cursor: pointer">
            &nbsp;&nbsp;&nbsp;<img src="/img/add_256.png" width="20" height="20" title="Adicionar Produto" />
        </a>
    </div>

    <div id="teste">                
    </div>
    
    <div class="formfield">
        <label for="">Desconto:</label>
        <input id="venda-valor_desconto" class="money" name="venda[valor_desconto]" type="text" size="21px" value=""/>
        
        <label for="">&nbsp;&nbsp;Valor Total:</label>
        <input id="venda-valor_total_venda" class="required money" name="venda[valor_total_venda]" type="text" size="21px" value=""/>
    </div>
    

    <div class="formfield">
        <label for="">Forma de Pagamento:</label>
        <?php echo $this->formSelect('venda[forma_pagamento]', $this->venda['forma_pagamento'], array('class' => 'required'), array(''=>'SELECIONE', 'D'=>'DINHEIRO', 'CC' => 'CARTÃO DE CRÉDITO', 'CD' => 'CARTÃO DE DÉBITO')); ?>        
    </div>
    
    <div class="formfield">
        <label for="">Tipo de Pagamento:</label>
        <?php echo $this->formSelect('venda[tipo_pagamento]', $this->venda['tipo_pagamento'], array('class' => 'required'), array(''=>'SELECIONE','V'=>'A VISTA', 'P' => 'A PRAZO')); ?>        
    </div>

           

    <div class="formbutton">
        <input id="btEnviar" type="submit" value="Enviar" />
        <button type="button" id="btVoltarVenda">Voltar</button> 
    </div>
</form>

<div id="sucessoVenda">
    <p>Sucesso</p>
</div>


<script>
    var dataForm = <?php echo Zend_Json::encode(array('venda' => $this->venda)); ?>;
    var dataAutoCompleteCliente = <?php echo $this->dataAutoCompleteCliente; ?>;
        
    $(function(){                
        $('#formVenda').populate(dataForm);
        
        $('.money').maskMoney({
            allowZero:true,
            decimal:",", 
            thousands:".", 
            defaultZero:false
        });
        $('#venda-data_venda').mask("99/99/9999");
        $('#venda-data_venda').datepicker({dateFormat:'dd/mm/yy'});
        
        $('#sucessoVenda').dialog({
            autoOpen: false
        });
        
        
        $.expr[':'].textEquals = function (a, i, m) {
        return $(a).text().match("^" + escape_regexp(m[3]) + "$");
    };
        $("#venda-nome").autocomplete({
            source: dataAutoCompleteCliente,
            autoFill:true,	
            mustMatch:true,           
            formatItem: function(row, ui, total) {
                return ui.item.value;
            }, 
            formatResult: function(row, ui) { 
                return ui.item.value;
            },
            formatMatch: function(row, ui){
                return ui.item.value;
            },
            change: function (event, ui) {
                if (!ui.item) {
                 $(this).val('');
                }
            },
            select: function(e, ui) {                                  
                if(ui.item.id == '') {
                    $('#venda-id_cliente').val('');
                    $("#venda-nome").val('');
                } else {
                    $('#venda-id_cliente').val(ui.item.id);
                    result = ui.item.value.split(" - ");
                    //alert(result[0]);
                    $(this).val(result[0]);
                    
                }
                return false;
            }            
       });
        
//        $('input#venda-nome').result(function(event, data, formatted) {
//            if(!data) {
//               $('#venda-id_cliente').val('');
//               $("#venda-nome").val('');
//           } else {
//               $('#venda-id_cliente').val(data.id);
//           }
//           alert(data.id);
//           });
        
        
        $('#formVenda').validate({
            submitHandler: function(form){
                jQuery(form).ajaxSubmit({
                    dataType:  'json', 
                    success: function(r){
                        if(r.tipo == 'sucesso'){                    
                            $('#sucessoVenda p').html(r.msg);
                            $('#sucessoVenda').dialog("open");
                            $( "#sucessoVenda" ).dialog({
                                modal: true,
                                buttons: {
                                    Ok: function() {
                                        $(this).dialog("close");
                                        window.location = r.url;
                                    }
                                }
                            });
                            
                            //$('#divMsg').html(r.msg)
                            //window.location = r.url;
                        } else {
                            $('#sucessoVenda p').html(r.msg);
                            $('#sucessoVenda').dialog("open");
                            $( "#sucessoVenda" ).dialog({
                                modal: true,
                                buttons: {
                                    Ok: function() {
                                        $(this).dialog("close");
                                        window.location = r.url;
                                    }
                                }
                                
                            });
                        }
          
                    } 
                });
            }
        });
        
        $('#btVoltarVenda').click(function(){
            $('#ui-tabs-1').load('/venda/index/menu/1');
        })
        
        var html;
        
        html = "<div class='formfield'>" +
            "<label for=''>Produto:</label>" +
            "<input class='required' id='produto' name='produto' type='text' size='50'/>" +
            "<label style='width: 100px' for=''>&nbsp;&nbsp;Quantidade:</label>" +
            "<input class='required' id='qtde' name='qtde' type='text' size='5 value=''/>" +
            "<a id='btRemover' onClick='removerItem(this)' style='cursor: pointer'>" +
            "&nbsp;&nbsp;<img src='/img/symbol_remove.png' width='30' height='30' title='Remover Produto' />" +
            "</a>" +
            "</div>";
        
        $('#btAdicionar').click(function(){
            $("#teste").append(html);
        });
                               
    });
    
    function escape_regexp(text) {
        return text.replace(/[-[\]{}()*+?.,\\^$|#\s]/g, "\\$&");
    }
    
    function removerItem(obj) {
        $(obj).parent().remove();
        //alert("a");
    }
    
</script>