<h1><?php echo $this->titulo; ?></h1>

<div>
    <form action="" method="post">
        <div class="formfield">
            <label for="login">E-mail</label>
            <input type="text" name="login" id="login" maxlength="255"/>
        </div>
        <div class="formfield">
            <label for="senha">Senha:</label>
            <input type="password" name="senha" id="senha" maxlength="45"/>
        </div>
        <div class="formbutton">
            <input type="submit" value="enviar"/>
        </div>
    </form>
</div>

<script>
    
    $(function(){
      
        $('#btEnviar').click(function(){
            if($('#login').val() == ""){
                alert('Informe um login');
                $('#login').focus();
                return false;
            }
            
            if($('#senha').val() == ""){
                alert('Informe uma senha');
                $('#senha').focus();
                return false;
            }
            
        });              
    })
    
</script>
