<h1><?php echo $this->titulo; ?></h1>

<div>
    <form action="" method="post">
        <div class="formfield">
            <label for="login">E-mail</label>
            <input type="text" name="login" id="login" maxlength="255"/>
        </div>
        <div class="formfield">
            <label for="senha">Senha:</label>
            <input type="password" name="senha" id="senha" maxlength="45"/>
        </div>
        <div class="formbutton">
            <input id="btEnviar" type="submit" value="Entrar"/>
        </div>
    </form>
</div>

<div id="mensagem">
    <p></p>
</div>

<script>    
    $(function(){
        //Melhora aparência dos botões
        $( "input[type=submit], button" ).button();
        
        $( "#mensagem" ).dialog({
            autoOpen: false
        });
        
        $('#btEnviar').click(function(){
            if($('#login').val() == ""){
                $('#mensagem p').html("Informe um login");                            
                $('#mensagem').dialog({
                    modal: true,
                    buttons: {
                        Ok: function() {
                            $(this).dialog("close");                            
                        }
                    }
                });
                $('#mensagem').dialog("open");                
                $('#login').focus();
                return false;
            }
            
            if($('#senha').val() == ""){
                $('#mensagem p').html("Informe uma senha");                            
                    $('#mensagem').dialog({
                        modal: true,
                        buttons: {
                            Ok: function() {
                                $(this).dialog("close");                            
                        }
                    }
                });
                $('#mensagem').dialog("open");                
                $('#senha').focus();
                return false;
            }
            
    
        });              
    })    
</script>
