<h1><?php echo $this->titulo; ?></h1>

<!-- formulário -->

<form id="formTipoDespesa" action="/tipo-despesa/salvar" method="post" enctype="multipart/form-data">
    
    <div class="formfield">
        <label for="">Descrição:</label>
        <input class="required" id="descricao" name="descricao" type="text" size="30" value=""/>
    </div>

    <div class="formbutton">
        <input id="btEnviar" type="submit" value="Enviar" />
        <button type="button" id="btVoltarTipoDespesa">Voltar</button> 
    </div>
</form>

<div id="sucessoTipoDespesa">
    <p>Sucesso</p>
</div>


<script>

    $(function(){

        $( "#sucessoTipoDespesa" ).dialog({
            autoOpen: false
        });
        
        $("#data").datepicker({dateFormat:'dd/mm/yy'});
        
        //$('#form').populate(dataForm);
        
        $('#formTipoDespesa').validate({
            submitHandler: function(form){
                jQuery(form).ajaxSubmit({
                    dataType:  'json', 
                    success: function(r){
                        if(r.tipo == 'sucesso'){                    
                            $('#sucessoTipoDespesa p').html(r.msg);
                            $('#sucessoTipoDespesa').dialog("open");
                            $( "#sucessoTipoDespesa" ).dialog({
                                modal: true,
                                buttons: {
                                    Ok: function() {
                                        $(this).dialog("close");
                                        window.location = r.url;
                                    }
                                }
                            });
                            
                            //$('#divMsg').html(r.msg)
                            //window.location = r.url;
                        } else {
                            $('#sucessoTipoDespesa p').html(r.msg);
                            $('#sucessoTipoDespesa').dialog("open");
                            $( "#sucessoTipoDespesa" ).dialog({
                                modal: true,
                                buttons: {
                                    Ok: function() {
                                        $(this).dialog("close");
                                        window.location = r.url;
                                    }
                                }
                                
                            });
                        }
          
                    } 
                });
            }
        });
        
        $('#btVoltarTipoDespesa').click(function(){
            $('#ui-tabs-9').load('/tipo-despesa/index/menu/1');
        })
        
    });
</script>