<h1><?php echo $this->titulo; ?></h1>

<!-- formulário -->

<form id="formMercadoria" action="/mercadoria/salvar" method="post" enctype="multipart/form-data">
    <div class="formfield">
        <input class="required" id="mercadoria-id_mercadoria" name="mercadoria[id_mercadoria]" type="hidden" value=""/>
        <label style="width: 225px" for="">Descrição:</label>
        <input class="required" id="mercadoria-descricao" name="mercadoria[descricao]" type="text" maxlength="45" size="50" value=""/>
    </div>

    <div class="formfield">
        <label style="width: 225px" for="">Tipo de Mercadoria:</label>
        <?php echo $this->formSelect('mercadoria[id_tipomercadoria]', '', array('class' => 'required'), $this->dadosComboTipoMercadoria); ?>                
    </div>

    <div class="formfield">
        <label style="width: 225px" for="">Subtipo de Mercadoria:</label>
        <?php echo $this->formSelect('mercadoria[id_subtipomercadoria]', '', array('class' => 'required'), $this->dadosComboSubTipoMercadoria); ?>                
    </div>
    
    <div class="formfield">
        <label style="width: 225px" for="">Quantidade em estoque:</label>
        <input class="required numeric" id="mercadoria-qtde_estoque" name="mercadoria[qtde_estoque]" type="text" size="15" maxlength="11" value=""/>
    </div>
    
    <div class="formfield">
        <label style="width: 225px" for="">Quantidade mínima em estoque:</label>
        <input class="required numeric" id="mercadoria-qtde_minima_estoque" name="mercadoria[qtde_minima_estoque]" type="text" size="15" maxlength="11" value=""/>
    </div>
    
    <div class="formfield">
        <label style="width: 225px" for="">Preço venda unitário:</label>
        <input class="required money" id="mercadoria-preco_venda_unitario" name="mercadoria[preco_venda_unitario]" type="text" size="15" maxlength="11" value=""/>
    </div>
    
    <div class="formbutton">
        <input id="btEnviar" type="submit" value="Enviar" />
        <button type="button" id="btVoltarMercadoria">Voltar</button> 
    </div>
</form>

<div id="sucessoMercadoria">
    <p>Sucesso</p>
</div>


<script>
    var dataForm = <?php echo Zend_Json::encode(array('mercadoria' => $this->mercadoria)); ?>;
    
    $(function(){
        $('#formMercadoria').populate(dataForm);
        
        //Melhora aparência dos botões
        $( "input[type=submit], button" ).button();
        
        //Adiciona mascaras nos campos numericos
        $('.money').maskMoney({
            allowZero:true,
            decimal:",", 
            thousands:".", 
            defaultZero:false
        });
        $('.numeric').numeric();
        
        //Combo de tipo mercadoria popula o combo do subtipomercadoria
        $('#mercadoria-id_tipomercadoria').change(function(){                        
            jsonComboSubTipoMercadoria = $.getJSON('/subtipo/json-combo-subtipomercadoria/id_tipomercadoria/' + $(this).val(), null, function(data){
                $('#mercadoria-id_subtipomercadoria').populateSelectJson(data);                
               
                /** se existir apenas 1 registros no retorno da combo, então seleciona esse registro e dispara o onchange da combo*/
                if($('#mercadoria-id_subtipomercadoria').find('option[value!=""]').length == 1){
                    $('#mercadoria-id_subtipomercadoria').find('option[value!=""]:first').attr('SELECTED',true);
                    $('#mercadoria-id_subtipomercadoria').change();
                }               
            });            
        });
        
        
        $( "#sucessoMercadoria" ).dialog({
            autoOpen: false
        });
        
        $("#data").datepicker({dateFormat:'dd/mm/yy'});
        
        //$('#form').populate(dataForm);
        
        $('#formMercadoria').validate({
            submitHandler: function(form){
                jQuery(form).ajaxSubmit({
                    dataType:  'json', 
                    success: function(r){
                        if(r.tipo == 'sucesso'){                    
                            $('#sucessoMercadoria p').html(r.msg);
                            
                            $( "#sucessoMercadoria" ).dialog({
                                modal: true,
                                buttons: {
                                    Ok: function() {
                                        $(this).dialog("close");
                                        window.location = r.url;
                                    }
                                }
                            });
                            
                            $('#sucessoMercadoria').dialog("open");
                            //$('#divMsg').html(r.msg)
                            //window.location = r.url;
                        } else {
                            $('#sucessoMercadoria p').html(r.msg);
                            
                            $( "#sucessoMercadoria" ).dialog({
                                modal: true,
                                buttons: {
                                    Ok: function() {
                                        $(this).dialog("close");
                                        window.location = r.url;
                                    }
                                }
                                
                            });
                            
                            $('#sucessoMercadoria').dialog("open");
                        }
          
                    } 
                });
            }
        });
        
        $('#btVoltarMercadoria').click(function(){
            $('#ui-tabs-8').load('/mercadoria/index/menu/1');
        })
        
    });
</script>