<table>
    <tr>
        <th>Nome</th>
        <th>E-email</th>
        <th>Ações</th>
    </tr>

    <tr class="alt" >
        <?php foreach ($this->paginator as $k => $usuarios): ?>
        <tr class="<?php echo ($k % 2 == 0) ? 'alt' : '' ?>">
            <td><?php echo $usuarios['nome'] ?></td>
            <td><?php echo $usuarios['email'] ?></td>

            <td>
                <a class="linkEditar" href="/usuario/formulario/id/<?php echo $usuario['id_usuario'] ?>">
                    <img src="/img/edit-icon.gif" title="Editar registro" />
                </a>
                <a class="btExcluir" href="/usuario/excluir/id/<?php echo $usuario['id_usuario'] ?>">
                    <img src="/img/delete-icon.gif" title="Excluir Registro" />
                </a>
            </td>
        </tr>    
    <?php endforeach; ?>

</table>

<?php echo $this->paginationControl($this->paginator, 'Sliding', 'my_pagination_control.phtml'); ?>

<div id="dcUsuario">
    <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>Deseja realmente excluir esse usuario?</p>
</div>

<div id="usuarioErro">
    <p>Erro</p>    
</div>

<div id="usuarioSucesso">
    <p>Sucesso</p>    
</div>

<script>
    
    var url = "";
    $(function(){       
                
        $( "#usuarioSucesso" ).dialog({
            autoOpen: false
        });
        
        $( "#usuarioErro" ).dialog({
            autoOpen: false
        });
                
        $("#dcUsuario").dialog({
            resizable: false,
            height:250,
            width:500,
            modal: true,
            autoOpen: false,
                
            buttons: {
                "Ok": function() {
                    $.get(url, null, function(retorno){
                        if(retorno.tipo == 'sucesso'){
                            $('#usuarioSucesso').html(retorno.msg);
                            $('#usuarioSucesso').dialog("open");
                            $('#usuarioSucesso').dialog({
                                buttons: {
                                    Ok: function() {
                                        $( this ).dialog( "close" );
                                    }
                                }
                            });
                                
                            $('#divResUsuario').load('/usuario/grid/nome/' + $('#nomeUsu').val());
                                
                        } else {
                            $('#usuarioErro').html(retorno.msg);
                            $('#usuarioErro').dialog("open");
                            $('#usuarioErro').dialog({
                                buttons: {
                                    Ok: function() {
                                        $( this ).dialog( "close" );
                                    }
                                }
                            });
                            $('#divResUsuario').load('/usuario/grid/nome/' + $('#nomeUsu').val());
                        }                    
                    }, 'json');
                    $( this ).dialog("close");
                    
                },
                Cancel: function() {
                    $('#divResUsuario').load('/usuario/grid/nome/' + $('#nomeUsu').val());
                    $( this ).dialog( "close" );
                        
                }
                    
            }
                
        });
                
        $('.pagination a').click(function(){
           
            var href = $(this).attr('href');
            $('#divResUsuario').load(href);
            return false;
        });
        
        $('.linkEditar').click(function(){
            var url = $(this).attr('href');
            $('#ui-tabs-3').load(url);
            return false;
        });
        
        $('.btExcluir').click(function(){
            
            url = $(this).attr('href');
            $("#dcUsuario").dialog("open");
            
            return false;
        });
        
    })
    
</script>