<h1><?php echo $this->titulo; ?></h1>

<div id="menuRelatorios">
    <h3>Relatório de Mercadorias</h3>
    <div>
        <form action="" method=get">            
            <div class="formfield">
                <label for="">Tipo:</label>
                <?php echo $this->formSelect('relatorio_mercadoria[id_tipomercadoria]', '', null, $this->dadosComboTipoMercadoria); ?>        
            </div>

            <div class="formfield">
                <label for="">Subtipo:</label>
                <?php echo $this->formSelect('relatorio_mercadoria[id_subtipomercadoria]', '', null, array(''=>'')); ?>        
            </div>

            <div class="formbutton">
                <button id="btGerarRelatorioMercadorias" type="button">Gerar Relatório</button>                
            </div>
        </form>
    </div>
    
    <h3>Relatório de Movimentação do Caixa</h3>
        <div>
            <p>
                <form action="" method=get">            
                     <div class="formfield">
                        <label for="dataInicialMovimentacaoCaixa">Data Inicial:</label>
                        <input id="dataInicialMovimentacaoCaixa" name="dataInicialMovimentacaoCaixa" type="text">               
                    </div>

                    <div class="formfield">
                        <label for="dataFinalMovimentacaoCaixa">Data Final:</label>
                        <input id="dataFinalMovimentacaoCaixa" name="dataFinalMovimentacaoCaixa" type="text">             
                    </div>

                    <div class="formbutton">
                        <button id="btGerarRelatorioMovimentacaoCaixa" type="button">Gerar Relatório</button>                
                    </div>
                </form>            
            </p>
        </div>    
</div>

<script>
    $(function(){
        //Melhora aparência dos botões
        $("input[type=submit], button").button();
        
        $("#menuRelatorios").accordion();
        
        //Combo de tipo mercadoria popula o combo do subtipomercadoria
        $('#relatorio_mercadoria-id_tipomercadoria').change(function(){
            if($('#relatorio_mercadoria-id_tipomercadoria').val() != '') {
                jsonComboSubTipoMercadoria = $.getJSON('/subtipo/json-combo-subtipomercadoria/id_tipomercadoria/' + $(this).val(), null, function(data){
                    $('#relatorio_mercadoria-id_subtipomercadoria').populateSelectJson(data);                

                    /** se existir apenas 1 registros no retorno da combo, então seleciona esse registro e dispara o onchange da combo*/
                    if($('#relatorio_mercadoria-id_subtipomercadoria').find('option[value!=""]').length == 1){
                        $('#relatorio_mercadoria-id_subtipomercadoria').find('option[value!=""]:first').attr('SELECTED',true);
                        $('#relatorio_mercadoria-id_subtipomercadoria').change();
                    }               
                });
            }            
        });
        
        $("#btGerarRelatorioMercadorias").click(function(){
            id_tipomercadoria = $('#relatorio_mercadoria-id_tipomercadoria').val();
            id_subtipomercadoria = $('#relatorio_mercadoria-id_subtipomercadoria').val();
            window.open('/relatorio/relatorio-mercadorias/id_tipomercadoria/' + id_tipomercadoria + '/id_subtipomercadoria/' + id_subtipomercadoria);            
        });
        
        //Data utilizadaos no relatorio de Movimentacao do Caixa
        $('#dataInicialMovimentacaoCaixa').mask("99/99/9999");
        $('#dataFinalMovimentacaoCaixa').mask("99/99/9999");
        $("#dataInicialMovimentacaoCaixa").datepicker({dateFormat:'dd/mm/yy'});     
        $("#dataFinalMovimentacaoCaixa").datepicker({dateFormat:'dd/mm/yy'});
       
        $("#btGerarRelatorioMovimentacaoCaixa").click(function(){
            data_inicial = urlencodeGet($('#dataInicialMovimentacaoCaixa').val());
            data_final = urlencodeGet($('#dataFinalMovimentacaoCaixa').val());
            window.open('/relatorio/relatorio-movimentacao-caixa/data_inicial/' + data_inicial + '/data_final/' + data_final);           
        });
    });
</script>