<?php
/** incia a captura do conteudo que sera renderizado como PDF */
ob_start();
?>
<style type="text/css">            
    .styleTD
    {
        font-size:10px; 
        border-bottom:1px solid #000000; 
        border-right:1px solid #000000; 
        padding:2px; 
        border-top:0px;
    }
    
    .styleTDTitulo
    {
        font-size:10px; 
        border-bottom:1px solid #000000; 
        border-right:1px solid #000000; 
        padding:2px; 
        border-top:1px solid #000000;
        background-color: #74b2e2;
    }         
</style>

<page backtop="7mm" backbottom="7mm" backleft="7mm" backright="7mm" style="font-size: 10pt">
    <page_header>
        <table style="border: solid 1px #000000; border-top:0px; border-left:0px; border-right:0px; border-bottom: 0px; padding: 5px; width: 100%; text-align: center;">
            <tr>           
                <td style="width: 100%; font-size: 16px;">
                    <b><?php echo strtoupper("SISTEMA LOJA") ?></b>                                                          
                </td>               
            </tr>            
        </table>
    </page_header>
    
    <page_footer>
        <table style="width: 100%; border: solid 1px black;">
            <tr>
                <td style="text-align: left;	width: 50%"><?php echo $this->utf8("Relatório de Movimentação do Caixa")->decode(); ?></td>
                <td style="text-align: right;	width: 50%"><?php echo $this->utf8("Página")->decode(); ?> [[page_cu]] de [[page_nb]]</td>
            </tr>
        </table>
    </page_footer>

    <br/><br/>

    <div style="text-align: center; width: 100%; font-weight: bold; font-size: 16px;">
        <?php echo $this->utf8("RELATÓRIO DE MOVIMENTAÇÃO DO CAIXA")->decode(); ?>
    </div>

    <br/><br/>   

    <br/><br/>
    
    <b>Per&iacute;odo: </b>
    <?php 
        if(!empty($this->params['data_inicial'])) {
            echo $this->String($this->params['data_inicial'])->reverseDate();
        } else {
            echo "__/__/____";
        }       
    ?>
    &agrave;
    <?php 
        if(!empty($this->params['data_final'])) {
            echo $this->String($this->params['data_final'])->reverseDate();
        } else {
            echo "__/__/____";
        }       
    ?>
    <br/><br/>
    <table border='1' style='border:1px solid #000000; border-collapse:collapse; font-size:9px;'>
        <thead>
        <tr style="font-size: 12;">
            <th class="styleTDTitulo" style="text-align: center">
                Movimento
            </th>
            <th class="styleTDTitulo" style="text-align: center">
                Data Realiza&ccedil;&atilde;o
            </th>
            <th class="styleTDTitulo" style="text-align: center">
                Valor Recebido
            </th>
            <th class="styleTDTitulo" style="text-align: center">
                Valor Pago 
            </th>            
        </tr>
        </thead>
        
        <?php
        
        $widthMovimento = 'width: 300px';
        $data = 'width: 170px';
        $valorRecebido = 'width: 100px';
        $valorPago = 'width: 100px';        
        
        if (!empty($this->dataVendas) || !empty($this->dataDespesas)) {
            //Para fazer linhas cor sim cornão
            $exibe_cor = false;            
            
            $somaValorRecebido = 0;
            $somaValorPago = 0;
            
            foreach ($this->dataVendas as $venda) {
                //Para fazer linhas cor sim cornão
                if ($exibe_cor) {
                    $cor = '#F0FFFF';
                    $exibe_cor = false;
                } else {
                    $cor = '#FFFFFF';
                    $exibe_cor = true;
                }                                
                
                $somaValorRecebido += $venda['valorRecebido'];
                if($venda['valorRecebido'] != 0) {
            ?>
                <tr>
                    <td style="<?=$widthMovimento?>;background-color:<?php echo $cor ?>">
                        <?php 
                            echo "VENDA PARA O CLINTE: ".$venda['nome']; 
                        ?>
                    </td>
                    <td style="<?=$data?>;text-align: center;background-color:<?php echo $cor ?>">
                        <?= $this->String($venda['data_venda'])->reverseDate(); ?>
                    </td>
                    <td style="<?=$valorRecebido?>;text-align: center;background-color:<?php echo $cor ?>">
                        <?= $this->String($venda['valorRecebido'])->floatToMoney(); ?>
                    </td>
                    <td style="<?=$valorPago?>;text-align: center;background-color:<?php echo $cor ?>">
                        <?php 
                            echo "-";
                        ?>
                    </td>                                       
                </tr>                
            <?php
                }
            }                                    
            ?>
                
            <?php
            foreach ($this->dataDespesas as $despesa) {
                //Para fazer linhas cor sim cornão
                if ($exibe_cor) {
                    $cor = '#F0FFFF';
                    $exibe_cor = false;
                } else {
                    $cor = '#FFFFFF';
                    $exibe_cor = true;
                }                                
                
                $somaValorPago += $despesa['valor_pago'];
                if($despesa['valor_pago'] != 0) {
            ?>
                <tr>
                    <td style="<?=$widthMovimento?>;background-color:<?php echo $cor ?>">
                        <?php 
                            echo "DESPESA: ".$despesa['descricao']; 
                        ?>
                    </td>
                    <td style="<?=$data?>;text-align: center;background-color:<?php echo $cor ?>">
                        <?= $this->String($despesa['data_pagamento'])->reverseDate(); ?>
                    </td>
                    <td style="<?=$valorRecebido?>;text-align: center;background-color:<?php echo $cor ?>">
                        <?php 
                            echo "-";
                        ?>
                    </td>
                    <td style="<?=$valorPago?>;text-align: center;background-color:<?php echo $cor ?>">
                        
                        <?= $this->String($despesa['valor_pago'])->floatToMoney(); ?>
                    </td>                                       
                </tr>                
            <?php
                }
            }                                    
            ?>
                <tr>
                    <td colspan="2" style="text-align: right;background-color:#CDCDB4">
                        <b>TOTAL</b>
                    </td>
                    <td  style="text-align: center;background-color:#CDCDB4">
                        <b><?= $this->String($somaValorRecebido)->floatToMoney()?></b>
                    </td>                    
                    <td  style="text-align: center;background-color:#CDCDB4">
                        <b><?= $this->String($somaValorPago)->floatToMoney()?></b>
                    </td>
                </tr>
                <?php 
                    $resultado = $somaValorRecebido - $somaValorPago;
                    if($resultado >= 0) {
                        $corResultado = "greenyellow";
                    } else {
                        $corResultado = "red";
                    }                    
                ?>
                <tr>
                    <td colspan="2" style="text-align: right;background-color: <?=$corResultado?>">
                        <b>
                            <?php 
                                if($resultado >= 0) {
                                    echo "LUCRO";
                                } else {
                                    echo "PREJUIZO";
                                }
                            ?>
                        </b>
                    </td>
                    <td  colspan="2" style="text-align: center;background-color: <?=$corResultado?>">
                        <b><?= $this->String($resultado)->floatToMoney()?></b>
                    </td>                                        
                </tr>
                
        <?php        
        } else {
        ?>            
            <tr>
                <td colspan="4" class="styleTD" style="width: 680px;">
                    Nenhuma movimenta&ccedil;&atilde;o encontrada, tente escolher outros filtros e gere novamente o relat&oacute;rio.
                </td>
            </tr>           
        <?php } ?>
    </table>
</page>

<?php
/** finaliza a captura do conteudo */

$content = ob_get_clean();
/** renderiza o PDF */
$orientation = 'P'; //L = PAISAGEM
//P = Porta Retrato
/** renderiza o PDF */
$this->pdf($content, 'RELATORIO_MOVIMENTACAO_CAIXA.pdf', null, $orientation);
?>
