<h1><?php echo $this->titulo; ?></h1>

<!-- formulário -->

<form id="formDespesa" action="/despesa/salvar" method="post" enctype="multipart/form-data">
    <div class="formfield">
        <label style="width: 140px" for="">Tipo da Despesa:</label>
        <input class="required" id="tipo-despesa" name="tipo-despesa" type="text" size="50" value=""/>
    </div>


    <div class="formfield">
        <label style="width: 140px" for="">Descrição:</label>
        <input class="required" id="descricao" name="descricao" type="text" maxlength="45" size="50" value=""/>
    </div>

    <div class="formfield">
        <label style="width: 140px" for="">Valor Total:</label>
        <input class="required" id="valor-total" name="valor-total" type="text" size="15" value=""/>
    </div>

    <br/>
    <h01>Parcela:</h01>
    <div class="formfield">
        <label style="width: 140px" for="">Valor da Parcela:</label>
        <input class="required" id="valor" name="valor" type="text" size="15" value=""/>
    </div>
    <div class="formfield">
        <label style="width: 140px" for="">Data Vencimento:</label>
        <input class="required" id="datepicker" name="data_vencimento" type="text" size="15" width="150px" value=""/>
        <label style="width: 150px; margin-left: 15px" for="">Data Pagamento:</label>
        <input class="required" id="date" name="data_pagamento" type="text" size="15" width="150px" value=""/>
    </div>
    
    <div class="formfield">
        <label style="width: 140px" for="">Valor do pagamento:</label>
        <input class="required" id="valor-pag" name="valor-pag" type="text" size="15" value=""/>
        <label style="width: 150px; margin-left: 15px" for="">Forma de Pagamento:</label>
        <select style="width: 149px" name="forma" class="required">
            <option selected value="">Selecione</option>
            <option value="dinheiro">Dinheiro</option>
            <option value="cartao">Cartão</option>
            <option value="cheque">Cheque</option>
            <option value="banco">Banco</option>
        </select>
    </div>
</div>

<div id="teste">


</div>
<div class="formbutton">
    <input id="btEnviar" type="submit" value="Enviar" />
    <button type="button" id="btVoltarDespesa">Voltar</button> 
</div>
</form>

<div id="sucessoDespesa">
    <p>Sucesso</p>
</div>


<script>

    $(function(){
        //Melhora aparência dos botões
        $( "input[type=submit], button" ).button();
        $( "#sucessoDespesa" ).dialog({
            autoOpen: false
        });
        
        $("#datepicker").datepicker({dateFormat:'dd/mm/yy'});
        $("#date").datepicker({dateFormat:'dd/mm/yy'});
        //$('#form').populate(dataForm);
        
        $('#formDespesa').validate({
            submitHandler: function(form){
                jQuery(form).ajaxSubmit({
                    dataType:  'json', 
                    success: function(r){
                        if(r.tipo == 'sucesso'){                    
                            $('#sucessoDespesa p').html(r.msg);
                            $('#sucessoDespesa').dialog("open");
                            $( "#sucessoDespesa" ).dialog({
                                modal: true,
                                buttons: {
                                    Ok: function() {
                                        $(this).dialog("close");
                                        window.location = r.url;
                                    }
                                }
                            });
                            
                            //$('#divMsg').html(r.msg)
                            //window.location = r.url;
                        } else {
                            $('#sucessoDespesa p').html(r.msg);
                            $('#sucessoDespesa').dialog("open");
                            $( "#sucessoDespesa" ).dialog({
                                modal: true,
                                buttons: {
                                    Ok: function() {
                                        $(this).dialog("close");
                                        window.location = r.url;
                                    }
                                }
                                
                            });
                        }
          
                    } 
                });
            }
        });
        
        $('#btVoltarDespesa').click(function(){
            $('#ui-tabs-10').load('/despesa/index/menu/1');
        })
       
        var html;
        
        html = "<div class='formfield'>" +
            "<label for=''>Parcela:</label>" +
            "<input class='required' id='parcela' name='parcela' type='text' size='50'/>" +
            "<label style='width: 80px' for=''>&nbsp;Quantidade:</label>" +
            "<input class='required' id='qtde' name='qtde' type='text' size='5 value=''/>" +
            "<a id='btRemover' style='cursor: pointer'>" +
            "&nbsp;&nbsp;<img src='/img/symbol_remove.png' width='30' height='30' title='Remover Produto' />" +
            "</a>" +
            "</div>";
        
        $('#btAdicionar').click(function(){
            $("#teste").append(html);
        });
       
    });
</script>