<table>
    <tr>
        <th>Descrição</th>
        <th>Tipo</th>
        <th>Valor</th>
        <th>Ações</th>
    </tr>

    <tr class="alt" >
        <?php foreach ($this->paginator as $k => $despesa): ?>
        <tr class="<?php echo ($k % 2 == 0) ? 'alt' : '' ?>">
            <td><?php echo $despesa['descricao'] ?></td>
            <td><?php echo $despesa['tipo'] ?></td>
            <td><?php echo $this->String($despesa['valor_despesa'])->floatToMoney(); ?></td>

            <td>
                <a class="linkEditar" href="/despesa/formulario/id/<?php echo $despesa['id_despesa'] ?>">
                    <img src="/img/edit-icon.gif" title="Editar registro" />
                </a>
                <a class="btExcluir" href="/despesa/excluir/id/<?php echo $despesa['id_despesa'] ?>">
                    <img src="/img/delete-icon.gif" title="Excluir Registro" />
                </a>
                <a class="btConsultarDespesa" href="/despesa/consultar/id/<?php echo $despesa['id_despesa'] ?>">
                    <img src="/img/lupa.png" title="Consultar Registro" />
                </a>
            </td>
        </tr>    
    <?php endforeach; ?>

</table>

<?php echo $this->paginationControl($this->paginator, 'Sliding', 'my_pagination_control.phtml'); ?>

<div id="dcDespesa">
    <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>Deseja realmente excluir esse compra?</p>
</div>

<div id="despesaErro">
    <p>Erro</p>    
</div>

<div id="despesaSucesso">
    <p>Sucesso</p>    
</div>

<script>
    
    var url = "";
    $(function(){                       
        $( "#despesaSucesso" ).dialog({
            autoOpen: false
        });
        
        $( "#despesaErro" ).dialog({
            autoOpen: false
        });
                
        $("#dcDespesa").dialog({
            resizable: false,
            height:250,
            width:500,
            modal: true,
            autoOpen: false,
                
            buttons: {
                "Ok": function() {
                    $.get(url, null, function(retorno){
                        if(retorno.tipo == 'sucesso'){
                            $('#despesaSucesso').html(retorno.msg);                            
                            $('#despesaSucesso').dialog({
                                modal: true,
                                autoOpen: false,
                                buttons: {
                                    Ok: function() {
                                        $( this ).dialog( "close" );
                                    }
                                }
                            });
                            $('#despesaSucesso').dialog("open");    
                            $('#divResDespesa').load('/despesa/grid/');
                                
                        } else {
                            $('#despesaErro').html(retorno.msg);                            
                            $('#despesaErro').dialog({
                                modal: true,
                                autoOpen: false,
                                buttons: {
                                    Ok: function() {
                                        $( this ).dialog( "close" );
                                    }
                                }
                            });
                            $('#despesaErro').dialog("open");                            
                            $('#divResDespesa').load('/despesa/grid/');
                        }                    
                    }, 'json');
                    $( this ).dialog("close");
                    
                },
                Cancel: function() {
                    $('#divResDespesa').load('/despesa/grid/');
                    $( this ).dialog( "close" );
                        
                }
                    
            }
                
        });
                
        $('.pagination a').click(function(){
           
            var href = $(this).attr('href');
            $('#divResDespesa').load(href);
            return false;
        });
        
        $('.linkEditar').click(function(){
            var url = $(this).attr('href');
            $('#ui-tabs-10').load(url);
            return false;
        });
        
        $('.btConsultarDespesa').click(function(){
            var url = $(this).attr('href');
            $('#ui-tabs-10').load(url);
            return false;
        });
        
        $('.btExcluir').click(function(){
            
            url = $(this).attr('href');
            $("#dcDespesa").dialog("open");
            
            return false;
        });
        
    })
    
</script>