<!-- formulário -->
<form action="" method="post" enctype="multipart/form-data">
    <div class="formfield">
        <label for="">Nome:</label>
        <input id="nome" name="nome" type="text"/>
    </div>
    <div class="formfield">
        <label for="">Sobrenome:</label>
        <input id="sobrenome" name="sobrenome" type="text"/>
    </div>
    <div class="formfield">
        <label for="">Celular:</label>
        <input id="celular" name="celular" type="text"/>
    </div>
    <div class="formfield">
        <label for="">Telefone:</label>
        <input id="telefone" name="telefone" type="text"/>
    </div>
    <div class="formfield">
        <label for="">E-mail:</label>
        <input id="email" name="email" type="text"/>
    </div>
    <div class="formfield">
        <label for="">Data Nasc.</label>
        <input id="data_nascimento" name="data_nascimento" type="text" />
        <small>(dd/mm/aaaa)</small>
    </div>
    <div class="formfield">
        <label for="">Foto:</label>
        <input type="file" name="foto" id="foto" />        
    </div>
    <div class="formfield">
        <label for="">Grupo:</label>
        <td> <?php echo $this->formSelect ('id_grupo',
                                                $this->contato['id_grupo'],
                                                array(),
                                                $this->dataCombo) ?>
        </td>  
    </div>
    <div class="formbutton">
        <input type="submit"  value="Enviar" />
        <button type="button" onclick="history.back()">Voltar</button> 
    </div>
</form>