<h1><?php echo $this->titulo; ?></h1>

<!-- formulário -->

<form id="formMercadoria" action="/mercadoria/salvar" method="post" enctype="multipart/form-data">
    <div class="formfield">
        <label style="width: 225px" for="">Descrição:</label>
        <input class="required" id="descricao" name="descricao" type="text" maxlength="45" size="50" value=""/>
    </div>

    <div class="formfield">
        <label style="width: 225px" for="">Tipo de Mercadoria:</label>
        <input class="required teste" id="tipo-merc" name="tipo-merc" type="text" size="30" value=""/>
    </div>

    <div class="formfield">
        <label style="width: 225px" for="">Subtipo de Mercadoria:</label>
        <input class="required teste" id="subtipo-merc" name="subtipo-merc" type="text" size="30" value=""/>
    </div>
    
    <div class="formfield">
        <label style="width: 225px" for="">Quantidade em estoque:</label>
        <input class="required teste" id="qtde-estoq" name="qtde-estoq" type="text" size="15" maxlength="11" value=""/>
    </div>
    
    <div class="formfield">
        <label style="width: 225px" for="">Quantidade mínima em estoque:</label>
        <input class="required teste" id="qtde-min-estoq" name="qtde-min-estoq" type="text" size="15" maxlength="11" value=""/>
    </div>
    
    <div class="formfield">
        <label style="width: 225px" for="">Preço venda unitário:</label>
        <input class="required teste" id="preco" name="preco" type="text" size="15" maxlength="11" value=""/>
    </div>
    
    <div class="formbutton">
        <input id="btEnviar" type="submit" value="Enviar" />
        <button type="button" id="btVoltarMercadoria">Voltar</button> 
    </div>
</form>

<div id="sucessoMercadoria">
    <p>Sucesso</p>
</div>


<script>

    $(function(){

        $( "#sucessoMercadoria" ).dialog({
            autoOpen: false
        });
        
        $("#data").datepicker({dateFormat:'dd/mm/yy'});
        
        //$('#form').populate(dataForm);
        
        $('#formMercadoria').validate({
            submitHandler: function(form){
                jQuery(form).ajaxSubmit({
                    dataType:  'json', 
                    success: function(r){
                        if(r.tipo == 'sucesso'){                    
                            $('#sucessoMercadoria p').html(r.msg);
                            $('#sucessoMercadoria').dialog("open");
                            $( "#sucessoMercadoria" ).dialog({
                                modal: true,
                                buttons: {
                                    Ok: function() {
                                        $(this).dialog("close");
                                        window.location = r.url;
                                    }
                                }
                            });
                            
                            //$('#divMsg').html(r.msg)
                            //window.location = r.url;
                        } else {
                            $('#sucessoMercadoria p').html(r.msg);
                            $('#sucessoMercadoria').dialog("open");
                            $( "#sucessoMercadoria" ).dialog({
                                modal: true,
                                buttons: {
                                    Ok: function() {
                                        $(this).dialog("close");
                                        window.location = r.url;
                                    }
                                }
                                
                            });
                        }
          
                    } 
                });
            }
        });
        
        $('#btVoltarMercadoria').click(function(){
            $('#ui-tabs-8').load('/mercadoria/index/menu/1');
        })
        
    });
</script>