<h1><?php echo $this->titulo; ?></h1>

<!-- formulário -->
<form id="formFornecedor" action="/fornecedor/salvar/id/<?php echo $this->fornecedor['id_fornecedor'] ?>"" method="post" enctype="multipart/form-data">
    <div class="formfield">
        <label for="">Razão Social:</label>
        <input class="required" id="razao_social" name="f[razao_social]" type="text" size="50" value=""/>
    </div>

    <div class="formfield">
        <label for="">Nome Fantasia:</label>
        <input class="required" id="nome_fantasia" name="f[nome_fantasia]" type="text" size="50" value=""/>
    </div>

    <div class="formfield">
        <label for="">CNPJ:</label>
        <input class="required" id="documento" name="f[documento]" type="text" size="30" value=""/>
    </div>

    <div class="formfield">
        <label for="">Representante:</label>
        <input class="required" id="representante_comercial" name="f[representante_comercial]" type="text" size="30" value=""/>
    </div>

    <div class="formfield">
        <label for="">Telefone:</label>
        <input class="required" id="telefone" name="f[telefone]" type="text" size="30" value=""/>
    </div>

    <div class="formfield">
        <label for="">E-mail:</label>
        <input class="required email" id="email" name="f[email]" type="text"  size="30" value="" />
    </div>
<br/>
  
        <h01>Endereço:</h01>
    <div class="formfield">
        <label for="">Rua:</label>
        <input class="required" id="rua" name="f[rua]" type="text"  size="33" value="" />
        <label style="width: 40px" for="">&nbsp;&nbsp;Nº:</label>
        <input class="required" id="numero" name="f[numero]" type="text"  size="10" value="" />
    </div>

    <div class="formfield">
        <label for="">Bairro:</label>
        <input class="required" id="bairro" name="f[bairro]" type="text"  size="20" value="" />
        <label style="width: 66px" for="">&nbsp; Cidade:</label>
        <input class="required" id="cidade" name="f[cidade]" type="text"  size="20" value="" />
    </div>

    <div class="formfield">
        <label for="">Estado:</label>
        <input class="required" id="estado" name="f[estado]" type="text"  size="20" value="" />
        <label style="width: 66px" for="">&nbsp;&nbsp;CEP:</label>
        <input class="required" id="cep" name="f[cep]" type="text"  size="20" value="" />
    </div>

    <div class="formbutton">
        <input id="btEnviar" type="submit" value="Enviar" />
        <button type="button" id="btVoltarFornecedor">Voltar</button> 
    </div>
</form>

<div id="sucessoFornForm">
    <p>Sucesso</p>
</div>


<script>
 var dataFormularioFornecedor = <?php echo Zend_Json::encode(array('f' => $this->fornecedor)) ?>;
    $(function(){
        
        $("#documento").mask("99.999.999/9999-99");
        $("#telefone").mask("(99) 9999-9999");
        $("#cep").mask("99999-999");
        
        $( "#sucessoFornForm" ).dialog({
            autoOpen: false
        });
        
        $('#formFornecedor').populate(dataFormularioFornecedor);
        
        $('#formFornecedor').validate({
            submitHandler: function(form){
                jQuery(form).ajaxSubmit({
                    dataType:  'json', 
                    success: function(r){
                        if(r.tipo == 'sucesso'){                    
                            $('#sucessoFornForm p').html(r.msg);
                            $('#sucessoFornForm').dialog("open");
                            $( "#sucessoFornForm" ).dialog({
                                modal: true,
                                buttons: {
                                    Ok: function() {
                                        $(this).dialog("close");
                                        window.location = r.url;
                                    }
                                }
                            });
                            
                            //$('#divMsg').html(r.msg)
                            //window.location = r.url;
                        } else {
                            $('#sucessoFornForm p').html(r.msg);
                            $('#sucessoFornForm').dialog("open");
                            $( "#sucessoFornForm" ).dialog({
                                modal: true,
                                buttons: {
                                    Ok: function() {
                                        $(this).dialog("close");
                                        window.location = r.url;
                                    }
                                }
                                
                            });
                        }
          
                    } 
                });
            }
        });
        
        $('#btVoltarFornecedor').click(function(){
            $('#ui-tabs-4').load('/fornecedor/index/menu/1');
        })
        
        
    });
</script>