<h1><?php echo $this->titlePage; ?></h1>
<form action="" method=get">
    <div class="formfield">
        <label for="">Razão Social:</label>
        <input id="nomeForn" name="nomeForn" type="text">
    </div>
    <div class="formbutton">
        <button id="btBuscarForn" type="button">Buscar</button>
        <button id="btNovoForn" type="button" value="/fornecedor/formulario">Novo</button> 
    </div>
</form>

<br />

<!-- grid para exibir os dados huehuehue -->
<div id="divResFornecedor">



</div>

<br />

<br />

<script>

    var fornecedorAutoComplete = <?php echo Zend_Json::encode($this->dadosAutoCompleteForn); ?>

    $(function(){
        //Melhora aparência dos botões
       $( "input[type=submit], button" ).button();
        $('#btNovoForn').click(function(){
            var url = $(this).attr('value');
            $('#ui-tabs-4').load(url);
            return false;
        });
    
    
        $( "#nomeForn" ).autocomplete({
            source: fornecedorAutoComplete
        });
    
        $('#divResFornecedor').load('/fornecedor/grid/nome/' + $('#nomeForn').val());
        $('#btBuscarForn').click(function(){
            var link = encodeURI('/fornecedor/grid/nome/' + $('#nomeForn').val());
            $('#divResFornecedor').load(link);
        });
    }); 
    
</script>