<table>
    <tr>
        <th>Nome</th>
        <th>Ações</th>
    </tr>

    <tr class="alt" >
        <?php foreach ($this->paginator as $k => $grupo): ?>

        <tr class="<?php echo ($k % 2 == 0) ? 'alt' : '' ?>">
            <td><?php echo $grupo['nome'] ?></td>        
            <td>
                <a class="btEditarGrupo" href="/grupo/formulario/id/<?php echo $grupo['id_grupo'] ?>">
                    <img src="/img/edit-icon.gif" title="Editar registro" />
                </a>
                <a id="btExcluirGrupo" href="/grupo/excluir/id/<?php echo $grupo['id_grupo'] ?>" >
                    <img src="/img/delete-icon.gif" title="Excluir Registro" />
                </a>
            </td>

        </tr>        
    <?php endforeach; ?>
</table>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'my_pagination_control.phtml'); ?>

<div id="dc">
    <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>Deseja realmente excluir esse grupo?</p>
</div>

<div id="erroGrupo">
    <p>Erro</p>    
</div>

<div id="sucessoGrupo">
    <p>Sucesso</p>    
</div>

<script>
    var url = "";
    
    $(function(){
        
        $( "#sucessoGrupo" ).dialog({
            autoOpen: false
        });
        
        $( "#erroGrupo" ).dialog({
            autoOpen: false
        });
        
        $("#dc").dialog({
            resizable: false,
            height:250,
            width:500,
            modal: true,
            autoOpen: false,
                
            buttons: {
                "Ok": function() {
                    $.get(url, null, function(retorno){
                        if(retorno.tipo == 'sucesso'){
                            $('#sucessoGrupo').html(retorno.msg);
                            $('#sucessoGrupo').dialog("open");
                            $('#sucessoGrupo').dialog({
                                buttons: {
                                    Ok: function() {
                                        $( this ).dialog( "close" );
                                    }
                                }
                            });
                                
                            $('#divResGrupo').load('/grupo/grid/nome/' + $('#nomeGru').val());
                                
                        } else {
                            $('#erroGrupo').html(retorno.msg);
                            $('#erroGrupo').dialog("open");
                            $('#erroGrupo').dialog({
                                buttons: {
                                    Ok: function() {
                                        $( this ).dialog( "close" );
                                    }
                                }
                            });
                            $('#divResGrupo').load('/grupo/grid/nome/' + $('#nomeGru').val());
                        }                    
                    }, 'json');
                    $( this ).dialog("close");
                    
                },
                Cancel: function() {
                    $('#divResGrupo').load('/grupo/grid/nome/' + $('#nomeGru').val());
                    $( this ).dialog( "close" );
                        
                }
                    
            }
                
        });
        
        $('.btEditarGrupo').click(function(){
            var url = $(this).attr('href');
            $('#ui-tabs-2').load(url);
            return false;
        });
        
        $('.pagination a').click(function(){      
            // $(this) pega o obj clicado
            var href = $(this).attr('href');
            $('#divResGrupo').load(href);
            return false;
        });
	
        $('#btExcluirGrupo').click(function(){
            url = $(this).attr('href');
            $("#dc").dialog("open");
            
            return false;
        });
        
    })
</script>