<div id="dialog-pesquisa-mercadoria" title="PESQUISA DE MERCADORIAS" style="display:none; padding:0px;">
    <fieldset>
        <legend>Pesquisar</legend>
        
        <div class="formfield">
            <label for="">Descrição:</label>
            <input id="selecionar-mercadoria-descricao" name="selecionar-mercadoria[descricao]" type="text" maxlength="45" size="30"/>
        <div>               
                    
        <div class="formbutton">        
            <button type="button" id="btnLocalizarMercadoria" onclick="localizarMercadoria()" title="Localizar">Localizar</button>
        </div>            
    </fieldset>
    
    <fieldset style="min-height:425px">
        <div id='div-grid-pesquisar-mercadoria'></div>
    </fieldset>
</div>

<div id="avisoPesquisa" title="ATENÇÃO">
    <p></p>
</div>            
            
<script>
    function configModalPesquisaMercadoria(){
        /** configura a modal */
        $("#dialog-pesquisa-mercadoria").dialog({
            autoOpen: false,
            height: '600',
            width: '800',
            modal: true,
            resizable: false,
            closeOnEscape: true,
            position: ['center', 'center']
        });
    }
    
    function closeModalPesquisaMercadoria(){			
        /** elimina a modal da memória */
        $("#dialog-pesquisa-mercadoria").dialog("close");
        /** fecha a modal ativando o click do botão de fechar */
        $('#dialog-pesquisa-mercadoria').prev('.ui-dialog-titlebar-close').click();
    }

    function openModalPesquisaMercadoria(){
        configModalPesquisaMercadoria();
        $("#dialog-pesquisa-mercadoria").dialog("open");
    }
    function localizarMercadoria() {
        descricao = urlencodeGet($.trim($('#selecionar-mercadoria-descricao').val()));                      
                        
        if($.trim(descricao).length > 2){            
            $(this).attr('disabled',true);
            url = '/mercadoria/pesquisar-mercadoria/descricao/'+descricao;
            $('#div-grid-pesquisar-mercadoria').load(url, function(data){
                $('#btnLocalizarMercadoria').attr('disabled',false);                    					
            });
        } else {
            $('#avisoPesquisa p').html('Insira no mínimo 3 caracteres para realizar a busca!');                
            $('#avisoPesquisa').dialog({
                modal: true,
                buttons: {
                    Ok: function() {
                        $(this).dialog("close");                            
                    }
                }
            });                                
            $('#avisoPesquisa').dialog("open");
        }
    }
    
    $(document).ready(function(){
        $('#avisoPesquisa').dialog({
            autoOpen: false
        });
               
        //para todos os inputs da modal de selcionar o funcionario, caso pressionado o enter deve ativar a pesquisa
        $('#dialog-pesquisa-mercadoria input').keypress(function(event){
            if(event.which == 13){				
                $('#btnLocalizarMercadoria').click();
            }
        });
                
    });
</script>