<h1><?php echo $this->titulo; ?></h1>

<!-- formulário -->

<form id="formSubtipo" action="/subtipo/salvar" method="post" enctype="multipart/form-data">
    <div class="formfield">
        <input class="required" id="subtipo-id_subtipomercadoria" name="subtipo[id_subtipomercadoria]" type="hidden" value=""/>
        <label for="">Tipo de Mercadoria:</label>
        <?php echo $this->formSelect('subtipo[id_tipomercadoria]', '', array('class' => 'required'), $this->dadosComboTipoMercadoria); ?>                
    </div>

    <div class="formfield">
        <label for="">Descrição:</label>
        <input class="required teste" id="subtipo-descricao" name="subtipo[descricao]" type="text" maxlength="45" size="50" value=""/>
    </div>
    
    <div class="formbutton">
        <input id="btEnviar" type="submit" value="Enviar" />
        <button type="button" id="btVoltarSubtipo">Voltar</button> 
    </div>
</form>

<div id="sucessoSubtipo">
    <p>Sucesso</p>
</div>


<script>
    //dados do subtipo que será editado, em caso de inserção fica vazio
    var dataForm = <?php echo Zend_Json::encode(array('subtipo' => $this->subtipo)); ?>;
    
    $(function(){
        //Melhora aparência dos botões
        $( "input[type=submit], button" ).button();
        
        $( "#sucessoSubtipo" ).dialog({
            autoOpen: false
        });
        
        //Preenche o formulario com base nos dados do subtipo
        $('#formSubtipo').populate(dataForm);
        
        $('#formSubtipo').validate({
            submitHandler: function(form){
                jQuery(form).ajaxSubmit({
                    dataType:  'json', 
                    success: function(r) {
                        if(r.tipo == 'sucesso') {                    
                            $('#sucessoSubtipo p').html(r.msg);
                            
                            $("#sucessoSubtipo").dialog({
                                modal: true,
                                buttons: {
                                    Ok: function() {
                                        $(this).dialog("close");
                                        window.location = r.url;
                                    }
                                }
                            });
                            $('#sucessoSubtipo').dialog("open");
                            
                            //$('#divMsg').html(r.msg)
                            //window.location = r.url;
                        } else {
                            $('#sucessoSubtipo p').html(r.msg);                           
                            $( "#sucessoSubtipo" ).dialog({
                                modal: true,
                                buttons: {
                                    Ok: function() {
                                        $(this).dialog("close");
                                        window.location = r.url;
                                    }
                                }
                                
                            });
                            $('#sucessoSubtipo').dialog("open");
                        }          
                    } 
                });
            }
        });
        
        $('#btVoltarSubtipo').click(function(){
            $('#ui-tabs-6').load('/subtipo/index/menu/1');
        })
        
    });
</script>