<h1><?php echo $this->titulo; ?></h1>

<!-- formulário -->

<form id="formSubtipo" action="/compra/salvar" method="post" enctype="multipart/form-data">
    <div class="formfield">
        <label for="">Tipo de Mercadoria:</label>
        <input class="required" id="tipo-merc" name="tipo-merc" type="text" size="50" value=""/>
    </div>

    <div class="formfield">
        <label for="">Descrição:</label>
        <input class="required teste" id="descricao" name="descricao" type="text" maxlength="45" size="50" value=""/>
    </div>
    <div class="formbutton">
        <input id="btEnviar" type="submit" value="Enviar" />
        <button type="button" id="btVoltarSubtipo">Voltar</button> 
    </div>
</form>

<div id="sucessoSubtipo">
    <p>Sucesso</p>
</div>


<script>

    $(function(){

        $( "#sucessoSubtipo" ).dialog({
            autoOpen: false
        });
        
        $("#data").datepicker({dateFormat:'dd/mm/yy'});
        
        //$('#form').populate(dataForm);
        
        $('#formSubtipo').validate({
            submitHandler: function(form){
                jQuery(form).ajaxSubmit({
                    dataType:  'json', 
                    success: function(r){
                        if(r.tipo == 'sucesso'){                    
                            $('#sucessoSubtipo p').html(r.msg);
                            $('#sucessoSubtipo').dialog("open");
                            $( "#sucessoSubtipo" ).dialog({
                                modal: true,
                                buttons: {
                                    Ok: function() {
                                        $(this).dialog("close");
                                        window.location = r.url;
                                    }
                                }
                            });
                            
                            //$('#divMsg').html(r.msg)
                            //window.location = r.url;
                        } else {
                            $('#sucessoSubtipo p').html(r.msg);
                            $('#sucessoSubtipo').dialog("open");
                            $( "#sucessoSubtipo" ).dialog({
                                modal: true,
                                buttons: {
                                    Ok: function() {
                                        $(this).dialog("close");
                                        window.location = r.url;
                                    }
                                }
                                
                            });
                        }
          
                    } 
                });
            }
        });
        
        $('#btVoltarSubtipo').click(function(){
            $('#ui-tabs-6').load('/subtipo/index/menu/1');
        })
        
    });
</script>