<h1><?php echo $this->titlePage; ?></h1>
<form action="" method=get">
    <div class="formfield">
        <label for="">Nome:</label>
        <input id="nomeCompra" name="nomeCompra" type="text">
    </div>
    <div class="formbutton">
        <button id="btBuscarCompra" type="button">Buscar</button>
        <button id="btNovaCompra" type="button" value="/compra/formulario">Novo</button> 
    </div>
</form>

<br />

<!-- grid para exibir os dados -->
<div id="divResCompra">

</div>

<br />

<br />

<script>

    var compraAutoComplete = <?php echo Zend_Json::encode($this->dadosAutoComplete); ?>

    $(function(){
    
        $('#btNovaCompra').click(function(){
            var url = $(this).attr('value');
            $('#ui-tabs-5').load(url);
            return false;
        });
    
    
        $( "#nomeCompra" ).autocomplete({
            source: compraAutoComplete
        });
    
        $('#divResCompra').load('/compra/grid/nome/' + $('#nomeCompra').val());
        $('#btBuscarCompra').click(function(){
        
            $('#divResCompra').load('/compra/grid/nome/' + $('#nomeCompra').val());
        });
    }); 
    
</script>