<h1><?php echo $this->titulo; ?></h1>

<h01>Gerar backup do banco</h01>

<div class="formbutton">
    <button type="button" id="btGerarBackup">Gerar</button> 
</div>

<script>
    $(function(){
        //Melhora aparência dos botões
        $( "input[type=submit], button" ).button();
        $("#btGerarBackup").click(function(){
            $('#ui-tabs-11').load('/manutencao/backup');
        });
       
    });
</script>